// <auto-generated />
using System;
using DoIt.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DoIt.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DoItDbContext))]
    partial class DoItDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DoIt.Domain.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("ToDoListId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_do_list_id");

                    b.HasKey("Id")
                        .HasName("pk_to_do_item");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_to_do_item_title");

                    b.HasIndex("ToDoListId")
                        .HasDatabaseName("ix_to_do_item_to_do_list_id");

                    b.ToTable("to_do_item");
                });

            modelBuilder.Entity("DoIt.Domain.ToDoList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_to_do_lists");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_to_do_lists_title");

                    b.ToTable("to_do_lists");
                });

            modelBuilder.Entity("DoIt.Domain.ToDoItem", b =>
                {
                    b.HasOne("DoIt.Domain.ToDoList", null)
                        .WithMany("Items")
                        .HasForeignKey("ToDoListId")
                        .HasConstraintName("fk_to_do_item_to_do_lists_to_do_list_id");
                });

            modelBuilder.Entity("DoIt.Domain.ToDoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
